source 'http://api.berkshelf.com'
cookbook 'yum'
cookbook 'runit'
cookbook 'build-essential', '>= 1.4.2', git: 'git://github.com/opscode-cookbooks/build-essential.git', tag: 'v1.4.2'
cookbook 'python', git: 'git://github.com/opscode-cookbooks/python.git'
cookbook 'conffile', git: 'git://github.com/optiflows-cookbooks/conffile.git'
cookbook 'gem_specific_install'
cookbook 'newrelic', git: 'git://github.com/escapestudios-cookbooks/newrelic.git'
cookbook 'uwsgi', git: 'git://github.com/blackrobot/chef-uwsgi.git'
cookbook 'supervisor', git: 'git://github.com/poise/supervisor.git'
cookbook 'logrotate', git: 'git://github.com/stevendanna/logrotate.git'
